"""initial schema

Revision ID: fdc4204ffb06
Revises: 
Create Date: 2026-05-28 14:37:22.891179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc4204ffb06'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('briefings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('article_ids_json', sa.Text(), nullable=False),
    sa.Column('score_version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_briefings'))
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('feed_url', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('source_priority', sa.Float(), nullable=False),
    sa.Column('paywalled', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('fetch_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('default_language', sa.String(), nullable=False),
    sa.Column('default_country_scope', sa.String(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('avg_items_per_fetch', sa.Float(), nullable=False),
    sa.Column('robots_policy_note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('slug', name=op.f('uq_sources_slug'))
    )
    op.create_table('story_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('representative_title', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('top_article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['top_article_id'], ['articles.id'], name=op.f('fk_story_clusters_top_article_id_articles'), ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story_clusters'))
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('name', name=op.f('uq_tags_name'))
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('raw_title', sa.String(), nullable=False),
    sa.Column('normalized_title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('canonical_url', sa.String(), nullable=False),
    sa.Column('dedup_hash', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('country_scope', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('urgency', sa.String(), nullable=False),
    sa.Column('reading_time_minutes', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scraping_method', sa.String(), nullable=False),
    sa.Column('paywalled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source_score', sa.Float(), nullable=False),
    sa.Column('freshness_score', sa.Float(), nullable=False),
    sa.Column('keyword_score', sa.Float(), nullable=False),
    sa.Column('category_score', sa.Float(), nullable=False),
    sa.Column('user_feedback_score', sa.Float(), nullable=False),
    sa.Column('novelty_score', sa.Float(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('score_explanation', sa.Text(), nullable=True),
    sa.Column('score_version', sa.String(), nullable=False),
    sa.Column('last_scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['story_clusters.id'], name=op.f('fk_articles_cluster_id_story_clusters'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_articles_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_articles')),
    sa.UniqueConstraint('dedup_hash', name=op.f('uq_articles_dedup_hash'))
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_cluster_id'), ['cluster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_score_version'), ['score_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_status'), ['status'], unique=False)

    op.create_table('source_fetch_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('items_seen', sa.Integer(), nullable=False),
    sa.Column('items_new', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_source_fetch_logs_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_fetch_logs'))
    )
    with op.batch_alter_table('source_fetch_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_fetch_logs_source_id'), ['source_id'], unique=False)

    op.create_table('ai_annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('technical_depth_score', sa.Float(), nullable=False),
    sa.Column('content_usefulness_score', sa.Float(), nullable=False),
    sa.Column('novelty_score', sa.Float(), nullable=False),
    sa.Column('actionability_score', sa.Float(), nullable=False),
    sa.Column('hype_penalty', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('why_relevant', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('content_angle', sa.Text(), nullable=True),
    sa.Column('extracted_entities_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_ai_annotations_article_id_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_annotations'))
    )
    with op.batch_alter_table('ai_annotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_annotations_article_id'), ['article_id'], unique=False)

    op.create_table('article_embeddings',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('text_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_article_embeddings_article_id_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'model_name', name=op.f('pk_article_embeddings'))
    )
    op.create_table('article_tags',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_article_tags_article_id_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_article_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'tag_id', name=op.f('pk_article_tags'))
    )
    op.create_table('article_uses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('use_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('content_angle', sa.Text(), nullable=True),
    sa.Column('possible_hook', sa.Text(), nullable=True),
    sa.Column('related_project', sa.String(), nullable=True),
    sa.Column('target_platform', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_article_uses_article_id_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_uses'))
    )
    with op.batch_alter_table('article_uses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_uses_article_id'), ['article_id'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_notes_article_id_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_article_id'), ['article_id'], unique=False)

    op.create_table('score_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('score_version', sa.String(), nullable=False),
    sa.Column('source_score', sa.Float(), nullable=False),
    sa.Column('freshness_score', sa.Float(), nullable=False),
    sa.Column('keyword_score', sa.Float(), nullable=False),
    sa.Column('category_score', sa.Float(), nullable=False),
    sa.Column('user_feedback_score', sa.Float(), nullable=False),
    sa.Column('novelty_score', sa.Float(), nullable=False),
    sa.Column('semantic_score', sa.Float(), nullable=True),
    sa.Column('llm_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_score_runs_article_id_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_score_runs'))
    )
    with op.batch_alter_table('score_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_score_runs_article_id'), ['article_id'], unique=False)

    op.create_table('user_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_user_actions_article_id_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_actions'))
    )
    with op.batch_alter_table('user_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_actions_article_id'), ['article_id'], unique=False)

    # ### end Alembic commands ###

    # Composite DESC index (expression index — autogenerate cannot render these).
    op.execute(
        "CREATE INDEX ix_articles_topic_final_score "
        "ON articles (topic, final_score DESC)"
    )

    # FTS5 full-text search over articles(title, summary, normalized_title),
    # external-content table backed by articles(id), kept in sync by 3 triggers.
    op.execute(
        """
        CREATE VIRTUAL TABLE articles_fts USING fts5(
            title,
            summary,
            normalized_title,
            content='articles',
            content_rowid='id'
        )
        """
    )
    op.execute(
        """
        CREATE TRIGGER articles_fts_ai AFTER INSERT ON articles BEGIN
            INSERT INTO articles_fts(rowid, title, summary, normalized_title)
            VALUES (new.id, new.title, new.summary, new.normalized_title);
        END
        """
    )
    op.execute(
        """
        CREATE TRIGGER articles_fts_ad AFTER DELETE ON articles BEGIN
            INSERT INTO articles_fts(articles_fts, rowid, title, summary, normalized_title)
            VALUES ('delete', old.id, old.title, old.summary, old.normalized_title);
        END
        """
    )
    op.execute(
        """
        CREATE TRIGGER articles_fts_au AFTER UPDATE ON articles BEGIN
            INSERT INTO articles_fts(articles_fts, rowid, title, summary, normalized_title)
            VALUES ('delete', old.id, old.title, old.summary, old.normalized_title);
            INSERT INTO articles_fts(rowid, title, summary, normalized_title)
            VALUES (new.id, new.title, new.summary, new.normalized_title);
        END
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS articles_fts_au")
    op.execute("DROP TRIGGER IF EXISTS articles_fts_ad")
    op.execute("DROP TRIGGER IF EXISTS articles_fts_ai")
    op.execute("DROP TABLE IF EXISTS articles_fts")
    op.execute("DROP INDEX IF EXISTS ix_articles_topic_final_score")
    with op.batch_alter_table('user_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_actions_article_id'))

    op.drop_table('user_actions')
    with op.batch_alter_table('score_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_runs_article_id'))

    op.drop_table('score_runs')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_article_id'))

    op.drop_table('notes')
    with op.batch_alter_table('article_uses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_uses_article_id'))

    op.drop_table('article_uses')
    op.drop_table('article_tags')
    op.drop_table('article_embeddings')
    with op.batch_alter_table('ai_annotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_annotations_article_id'))

    op.drop_table('ai_annotations')
    with op.batch_alter_table('source_fetch_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_fetch_logs_source_id'))

    op.drop_table('source_fetch_logs')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_status'))
        batch_op.drop_index(batch_op.f('ix_articles_score_version'))
        batch_op.drop_index(batch_op.f('ix_articles_published_at'))
        batch_op.drop_index(batch_op.f('ix_articles_content_hash'))
        batch_op.drop_index(batch_op.f('ix_articles_cluster_id'))

    op.drop_table('articles')
    op.drop_table('tags')
    op.drop_table('story_clusters')
    op.drop_table('sources')
    op.drop_table('briefings')
    # ### end Alembic commands ###
